# Generated by Django 4.0.1 on 2022-03-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReverseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='CommentsId',
            new_name='CommentId',
        ),
    ]
