# Generated by Django 4.0.1 on 2022-03-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReverseApp', '0003_remove_comments_userid_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Username',
            new_name='UserName',
        ),
    ]
